Adding search functionality to make scripting easier

diff --git a/gh-prop b/gh-prop
--- a/gh-prop
+++ b/gh-prop
@@ -11,6 +11,7 @@ Commands:
   list        List properties for a repository
   set         Set a property for a repository
   schema      Get the schema for an organization
+  search      Search for a matching property value in a repository
 
 Options:
   -r <owner/repo>   Specify the owner and repository name
@@ -23,6 +24,9 @@ Examples:
   gh prop set -r octocat/hello-world -p Team -v "Team A"
   gh prop schema
   gh prop schema octocat
+  gh prop search -v "Any value"
+  gh prop search -p "Team" -v "Team A"
+  gh prop search -r octocat/hello-world -p "Team" -v "Team A"
 }
 EOF
 }
@@ -88,6 +92,44 @@ schema() {
   -H "Accept: application/vnd.github+json" \
   -H "X-GitHub-Api-Version: 2022-11-28" \
   /orgs/"$owner"/properties/schema
+}
+
+search() {
+  local repo='{owner}/{repo}'
+  local prop
+  local value
+  if [ $# -eq 0 ]; then
+    usage && exit 1
+  fi
+
+  while getopts "r:p:v:" opt; do
+    case $opt in
+      r) repo="$OPTARG";;
+      p) prop="$OPTARG";;
+      v) value="$OPTARG";;
+      *) usage && exit 1;;
+    esac
+  done
+
+  if [ -z "$value" ]; then
+    echo "error: missing required option" >&2
+    usage && exit 1
+  fi
+
+  repo_props="$(gh prop list -r "${repo}")"
+
+  if [ -z "$prop" ]; then
+    result="$(echo "$repo_props" | jq ".[] | .value == \"${value}\"")"
+  else
+    result="$(echo "$repo_props" | jq ".[] | select(.property_name == \"${prop}\") | .value == \"${value}\"")"
+  fi
+
+  if [[ "$result" =~ "true" ]]; then
+    echo "✅ Found a match: '${repo}'"
+  else
+    echo "❌ No match: '${repo}'"
+    exit 1
+  fi
 }
 
 cmd="$1"
